### ISSUE TITLE
possibility to write paths

### ISSUE THREAD

**Issue by lepmik** [j4321/tkFileBrowser#18]
Hi, love tkfilebrowser, thank you for making it!

Feature request: Would be nice if one could write down a path in the file browser, like a text box in the top row, similar to nautilus in ubuntu if you are familiar with that.

**Comment by j4321** [comment]
Hello,

This feature already exists though I have not documented it: 
Press `Ctrl+L` and the box you want should appear.

By the way, here is a list of the existing keyboard bindings that I should add in the documentation:
- `Ctrl+L` toggle path entry visibility
- `Ctrl+H` toggle hidden files visibility
- `Ctrl+Shift+N` create a new folder (if enabled)
- `Alt+←/→` go to previous/next folder in navigation history
-  `Alt+↓/↑` go to parent/child folder

I based my keyboard bindings on the ones available in Thunar because I use this file manager, so maybe they are a bit different from the ones in Nautilus.

Thanks for using my module.

**Comment by lepmik** [comment]
great, all works and same as nautilus :+1:  

Thank you
